# Generated by Django 5.0.1 on 2024-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
