# Generated by Django 5.0.1 on 2024-02-20 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contacts", models.CharField(blank=True, max_length=100)),
                (
                    "files",
                    models.FileField(
                        blank=True, null=True, upload_to="media/profile_files"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="media/default_avatar.png",
                        upload_to="media/profile_images",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=600,
                        verbose_name="Description",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
