# Generated by Django 5.0.1 on 2024-02-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=600,
                        verbose_name="Description",
                    ),
                ),
            ],
        ),
    ]
