# Generated by Django 5.0.1 on 2024-02-22 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_info", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="description",
        ),
    ]
