# Generated by Django 5.0.1 on 2024-02-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_info", "0002_remove_user_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"], "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
