# Generated by Django 5.0.1 on 2024-02-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_info", "0003_alter_user_options_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=600, verbose_name="Description"
            ),
        ),
    ]
